---
development:
  dialect: postgres
  database: db_name
  user: db_user
  password: db_password
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://db_user:db_password@127.0.0.1:5432/db_name?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://db_user:db_password@127.0.0.1:5432/db_name?sslmode=disable"}}
